# Generated by Django 5.1.3 on 2026-03-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=120, unique=True)),
                ("current_level", models.CharField(max_length=120)),
                ("life", models.PositiveSmallIntegerField(default=3)),
                ("allies_rescued", models.PositiveIntegerField(default=0)),
                ("checkpoint", models.CharField(max_length=120)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
