# Generated by Django 5.1.3 on 2026-03-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprogress",
            name="campaign_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="playerprogress",
            name="save_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
