import{existsSync,readFileSync}from'node:fs';import{execFileSync}from'node:child_process';import{resolve}from'node:path';
const game=resolve(import.meta.dirname,'..'),repo=resolve(game,'..'),fail=[];const read=p=>JSON.parse(readFileSync(resolve(game,p),'utf8'));const manifest=read('public/assets/campaign/canonical_campaign_manifest.json');
const first=manifest.nodes.findIndex(n=>n.id==='lvl07-cin01-inicio-del-descenso'),exterior=manifest.nodes.findIndex(n=>n.id==='lvl10-esc01-combate-50-bajas-en-via-publica'),scope=manifest.nodes.slice(first,exterior);if(first!==17||exterior!==30||scope.length!==13)fail.push('scope must be derived as canonical indices 17..29');if(manifest.flowId!=='main_campaign'||manifest.nodes.length!==35)fail.push('canonical campaign changed');
const ids=['level_8_pasillo_subsuelo2_escaleras_subsuelo3','level_9_verificacion_salidas','level_9_subsuelo3_garage_salida'],required=['Background','DistantArchitecture','RearArchitecture','Architecture','RearProps','GameplayDecor','FrontProps','Foreground','LightingAnchors','AmbientZones','ReflectionZones','OcclusionZones','Collision','OneWayPlatforms','Stairs','PlayerSpawns','AllySpawns','EnemySpawns','SpawnAreas','Interactables','Triggers','Objectives','Checkpoints','Pickups','Exits','CameraBounds','NavigationHints'],signatures=new Set();
for(const id of ids){const m=read(`public/assets/tiled/maps/${id}.tmj`),layers=new Map(m.layers.map(l=>[l.name,l])),p=Object.fromEntries(m.properties.map(x=>[x.name,x.value]));for(const n of required)if(!layers.has(n))fail.push(`${id}: missing ${n}`);for(const n of required.slice(0,8))if(!layers.get(n)?.objects.length)fail.push(`${id}: empty ${n}`);if(!p.environmentKitIds)fail.push(`${id}: missing kit`);if(signatures.has(p.compositionSignature))fail.push(`${id}: repeated composition`);signatures.add(p.compositionSignature);const runtime=new Set();for(const n of required.slice(0,8))for(const o of layers.get(n).objects){const q=Object.fromEntries(o.properties.map(x=>[x.name,x.value]));if(!q.runtimeId||runtime.has(q.runtimeId))fail.push(`${id}: duplicate runtimeId`);runtime.add(q.runtimeId);for(const k of['assetKey','frame','depth','anchor','alpha','tint','scrollFactorX','scrollFactorY','visualRole'])if(q[k]===undefined)fail.push(`${o.name}: missing ${k}`)}const bounds=layers.get('CameraBounds').objects[0];for(const o of layers.get('EnemySpawns').objects)if(o.x<bounds.x||o.y<bounds.y||o.x>bounds.x+bounds.width||o.y>bounds.y+bounds.height)fail.push(`${id}: enemy out of bounds`)}
const descent=read('public/assets/levels/level8_descenso_temporizador.json'),dr=read('public/assets/levels/runtime/level_8_pasillo_subsuelo2_escaleras_subsuelo3.runtime.json');if(descent.timer.durationMs!==180000||!descent.timer.pausesDuring.includes('dialogue')||!descent.timer.resetOnDefeat||descent.completion.exitId!=='escalera-subsuelo-3')fail.push('timed descent contract incomplete');if(!dr.exits.some(x=>x.id===descent.completion.exitId))fail.push('timed descent concrete exit missing');
const exits=read('public/assets/levels/runtime/level_9_verificacion_salidas.runtime.json');if(exits.interactables.filter(x=>x.exitId).length!==5||new Set(exits.interactables.filter(x=>x.exitId).map(x=>x.exitId)).size!==5||exits.verificationProgress.total!==5)fail.push('five contextual exits required');
const garage=read('public/assets/levels/runtime/level_9_subsuelo3_garage_salida.runtime.json');if(garage.garageSectors.length!==9||new Set(garage.vehicles.map(x=>x.frame)).size<6||garage.vehicles.some(x=>x.floorContactY!==1080)||!garage.searchPersistence.preventDuplicateLoot)fail.push('garage sectors, grounded vehicle variety, or search persistence invalid');if(!garage.spawn_zones.points.length)fail.push('garage combat has zero spawns');
for(const kit of['lower-basement-kit','subsoil-three-kit','security-exit-kit','utility-corridor-kit','parking-garage-kit','garage-vehicle-kit','garage-damage-kit','industrial-lighting-kit']){if(!existsSync(resolve(game,`art-source/environment/${kit}.json`)))fail.push(`${kit} source missing`);if(!existsSync(resolve(game,`public/assets/production-art/environments/${kit}.png`)))fail.push(`${kit} generated atlas missing`);if(existsSync(resolve(game,'dist'))&&!existsSync(resolve(game,`dist/assets/production-art/environments/${kit}.png`)))fail.push(`${kit} dist atlas missing`)}
if(!existsSync(resolve(game,'public/assets/tiled/maps/level_10_exterior_urbano.tmj'))||!read('public/assets/tiled/maps/level_10_exterior_urbano.tmj').layers.find(x=>x.name==='PlayerSpawns')?.objects.length)fail.push('first exterior spawn missing');const png=execFileSync('git',['ls-files','game/public/assets/production-art/**/*.png'],{cwd:repo,encoding:'utf8'}).trim();if(png)fail.push(`tracked PNG: ${png}`);if(existsSync(resolve(repo,'.gitattributes'))&&/filter=lfs/.test(readFileSync(resolve(repo,'.gitattributes'),'utf8')))fail.push('Git LFS exists');
const original=execFileSync('git',['show','47a071d:game/public/assets/campaign/canonical_campaign_manifest.json'],{cwd:repo,encoding:'utf8'});if(original!==readFileSync(resolve(game,'public/assets/campaign/canonical_campaign_manifest.json'),'utf8'))fail.push('canon modified');
if(fail.length){console.error(fail.map(x=>`- ${x}`).join('\n'));process.exit(1)}console.log(`Lower-basement/garage audit passed: ${scope.length} canonical nodes, ${ids.length} distinct compositions, five exits, nine garage sectors, 35-node canon intact.`);
