import Phaser from 'phaser';import{TiledObjectParser}from'../tiled/TiledObjectParser';import{SurvivalColorGradePipeline,LocalizedVignettePipeline,WetSurfaceHighlightPipeline}from'./pipelines';import type{TiledMap,TiledObject}from'../tiled/TiledTypes';
export type LightingQuality='reduced'|'balanced'|'high';
export interface LightingSnapshot{lightCount:number;dynamicLightCount:number;activeRenderTextures:number;shaderPipeline:string;canvasFallback:boolean}
export class SurvivalLightingSystem{private effects:Phaser.GameObjects.GameObject[]=[];private timers:Phaser.Time.TimerEvent[]=[];private readonly fallback:boolean;constructor(private scene:Phaser.Scene,private map:TiledMap,private quality:LightingQuality='balanced'){this.fallback=scene.game.renderer.type===Phaser.CANVAS}
 create():LightingSnapshot{const shaderSources=[SurvivalColorGradePipeline,LocalizedVignettePipeline,WetSurfaceHighlightPipeline];if(shaderSources.some(source=>source.length===0))throw new Error('EMPTY_SHADER_SOURCE');const ambient=this.objects('AmbientZones');for(const zone of ambient){const p=TiledObjectParser.properties(zone.properties??[]),g=this.scene.add.graphics().setDepth(60).setBlendMode(Phaser.BlendModes.MULTIPLY);g.fillStyle(color(p.tint,0x18212a),number(p.alpha,.18));g.fillRect(zone.x,zone.y,zone.width,zone.height);this.effects.push(g)}for(const zone of this.objects('ReflectionZones')){const p=TiledObjectParser.properties(zone.properties??[]),g=this.scene.add.graphics().setDepth(7).setBlendMode(Phaser.BlendModes.ADD);g.fillStyle(0x91b8c7,number(p.reflectionStrength,.2));g.fillEllipse(zone.x+zone.width/2,zone.y+zone.height/2,zone.width,Math.min(zone.height,42));this.effects.push(g)}for(const zone of this.objects('OcclusionZones')){const p=TiledObjectParser.properties(zone.properties??[]),g=this.scene.add.graphics().setDepth(55).setBlendMode(Phaser.BlendModes.MULTIPLY);g.fillStyle(0x071016,number(p.alpha,.16));g.fillRoundedRect(zone.x,zone.y,zone.width,zone.height,24);this.effects.push(g)}const anchors=this.objects('LightingAnchors');for(const anchor of anchors){const p=TiledObjectParser.properties(anchor.properties??[]),g=this.scene.add.graphics().setDepth(58).setBlendMode(Phaser.BlendModes.ADD);g.fillStyle(color(p.tint,0xffd27a),this.fallback?.08:.13);g.fillCircle(anchor.x,anchor.y,this.quality==='high'?150:110);this.effects.push(g);if(!this.fallback&&this.quality!=='reduced'&&anchor.name.includes('emergency')){const timer=this.scene.time.addEvent({delay:1700,loop:true,callback:()=>g.setAlpha(g.alpha===1?.55:1)});this.timers.push(timer)}}return{lightCount:anchors.length,dynamicLightCount:this.timers.length,activeRenderTextures:0,shaderPipeline:this.fallback?'canvas-reduced':'phaser-blend-fallback',canvasFallback:this.fallback}}
 flash(x:number,y:number){const flash=this.scene.add.graphics().setDepth(70).setBlendMode(Phaser.BlendModes.ADD);flash.fillStyle(0xffcc76,.42);flash.fillCircle(x,y,72);this.effects.push(flash);this.scene.tweens.add({targets:flash,alpha:0,duration:70,onComplete:()=>{flash.destroy();this.effects=this.effects.filter(value=>value!==flash)}})}
 destroy(){for(const timer of this.timers)timer.remove(false);this.timers=[];for(const effect of this.effects)effect.destroy();this.effects=[]}
 private objects(name:string):TiledObject[]{return this.map.layers.find(layer=>layer.name===name)?.objects??[]}}
function number(value:string|number|boolean|undefined,fallback:number){return typeof value==='number'?value:fallback}function color(value:string|number|boolean|undefined,fallback:number){if(typeof value==='number')return value;if(typeof value==='string'&&/^(0x|#)?[0-9a-f]{6}$/i.test(value))return Number.parseInt(value.replace(/^0x|^#/,''),16);return fallback}
