import type { Anchor, EnvironmentInstance, EnvironmentRole, EnvironmentSector, LevelWorldDefinition, WorldConnector } from '../world/LevelWorldDefinition.ts';
import { worldAssetCatalog } from './worldAssetCatalog.ts';

interface Profile { nodeId:string; runtimeLevelId:string; profile:string; location:string; locationLabel:string; floor:string; floorLabel:string; elevation:number; landmark:string; connector:'door'|'stairUp'|'stairDown'|'officeAccess'|'garageRamp'|'vehicle'|'exteriorRoute'|'cinematicBoundary'; next:string; vertical?:'ascending'|'descending'; minimap:'interior'|'vertical'|'garage'|'exterior'; assetOffset:number }
const profiles:readonly Profile[]=[
 ['lvl01-esc01-comedor-resistencia','level_1_comedor_resistencia','subsuelo-dining-resistance','bank-central','Comedor institucional','subsuelo-1','Subsuelo · comedor',-1,'resistance-barricade','door','lvl01-esc02-pasillos-hacia-escaleras-pb',undefined,'interior',0],
 ['lvl01-esc02-pasillos-hacia-escaleras-pb','level_1_pasillos_escaleras_pb','service-corridor-ascent','bank-central','Pasillos de servicio','subsuelo-1','Subsuelo · acceso a PB',-1,'teller-security-line','stairUp','lvl01-cin01-cierre-contextual',undefined,'interior',3],
 ['lvl02-esc01-hall-planta-baja','level_2_hall_planta_baja','ground-floor-grand-hall','bank-central','Hall principal','planta-baja','Planta baja',0,'main-hall-core','stairUp','lvl02-cin01-ascenso-al-segundo-piso',undefined,'interior',6],
 ['lvl03-esc01-segundo-piso','level_3_segundo_piso','second-floor-administration','bank-central','Administración','piso-2','Segundo piso',2,'archive-glass-corridor','stairUp','lvl03-cin01-llamado-lorena-rescate',undefined,'interior',9],
 ['lvl04-esc01-tercer-piso','level_4_tercer_piso','third-floor-compromised','bank-central','Oficinas comprometidas','piso-3','Tercer piso',3,'collapsed-office-line','officeAccess','lvl04-cin01-rescate-lorena-en-oficina-422',undefined,'interior',12],
 ['lvl05-esc01-cuarto-piso-comedor','level_4_oficina_422_comedor_escaleras','upper-dining-fourth','bank-central','Comedor superior','piso-4','Cuarto piso · comedor',4,'upper-dining-windows','stairDown','lvl05-cin01-descenso-al-quinto-piso',undefined,'interior',15],
 ['lvl06-esc01-quinto-piso-pertenencias','level_5_oficinas_selene_descenso','fifth-floor-belongings','bank-central','Sector de pertenencias','piso-5','Quinto piso',5,'abandoned-lockers','stairDown','lvl06-cin01-reencuentro-y-salida-e',undefined,'interior',18],
 ['lvl07-esc01-oficina-422-rescate','level_6_pasillos_planta_baja_salidas','office-422-rescue','bank-central','Oficina 422','oficina-422','Cuarto piso · Oficina 422',4,'office-422-barricade','officeAccess','lvl07-cin01-inicio-del-descenso',undefined,'interior',21],
 ['lvl08-esc01-descenso-con-temporizador','level_8_pasillo_subsuelo2_escaleras_subsuelo3','timed-multiflight-descent','bank-central','Núcleo de escaleras','vertical-5-a-subsuelo-2','Descenso · múltiples bandas',5,'fire-stair-core','stairDown','lvl08-cin01-damian-infectado-y-suicidio','descending','vertical',24],
 ['lvl09-esc01-verificacion-salidas','level_9_verificacion_salidas','exit-verification-sublevel','bank-central','Sector de salidas','subsuelo-2','Subsuelo 2 · salidas',-2,'distinct-exit-bank','garageRamp','lvl09-cin01-hallazgo-salida-y-mordida-selene',undefined,'interior',27],
 ['lvl10-esc01-garage-busqueda-vehiculo','level_9_subsuelo3_garage_salida','garage-vehicle-search','bank-garage','Garage · búsqueda','subsuelo-3','Subsuelo 3 · garage',-3,'target-escape-vehicle','vehicle','lvl10-cin01-hallazgo-del-vehiculo',undefined,'garage',30],
 ['lvl10-esc02-resistencia-en-garage','level9_b3_estacionamiento_canonico','garage-resistance','bank-garage','Garage · resistencia','subsuelo-3','Subsuelo 3 · garage',-3,'vehicle-defense-barricade','vehicle','lvl10-cin02-salida-del-garage',undefined,'garage',34],
 ['lvl10-esc01-combate-50-bajas-en-via-publica','level10','plaza-de-mayo-street-hold','buenos-aires','Vía pública · Plaza de Mayo','exterior-plaza','Exterior · Plaza de Mayo',0,'plaza-street-front','exteriorRoute','lvl10-cin02-cierre-duo-final-en-san-telmo',undefined,'exterior',38],
 ['lvl10-esc03-llegada-a-san-telmo','level_10_llegada_san_telmo','san-telmo-final-route','san-telmo','San Telmo','exterior-san-telmo','Exterior · San Telmo',0,'san-telmo-corner','cinematicBoundary','lvl10-cin03-desenlace-abierto',undefined,'exterior',43]
].map(row=>({nodeId:row[0],runtimeLevelId:row[1],profile:row[2],location:row[3],locationLabel:row[4],floor:row[5],floorLabel:row[6],elevation:row[7],landmark:row[8],connector:row[9],next:row[10],vertical:row[11],minimap:row[12],assetOffset:row[13]} as Profile));

const roles:readonly EnvironmentRole[]=['structure','rearArchitecture','wall','rearDecor','playfieldDecor','prop','landmark','lightFixture'];
const makeInstances=(profile:Profile,sectors:readonly EnvironmentSector[]):EnvironmentInstance[]=>Array.from({length:24},(_,index)=>({assetKey:worldAssetCatalog[(profile.assetOffset+index*3)%worldAssetCatalog.length].key,x:80+(index%8)*245,y:sectors[index%3].y+sectors[index%3].height-36-(index%4)*31,originX:0,originY:1,scaleX:index%5===0?1.12:1,scaleY:index%7===0?1.08:1,flipX:index%4===1,alpha:index%9===0?.88:1,depth:1+(index%8),scrollFactorX:index%6===0?.92:1,scrollFactorY:1,sectorId:sectors[index%3].sectorId,role:roles[index%roles.length],optionalVariant:`${profile.profile}-${index+1}`,optionalLightAnchorId:index%8===7?'light-primary':undefined}));
const connector=(p:Profile,id:string,kind:Profile['connector'],x:number,destination:string):WorldConnector=>({connectorId:id,kind,x,y:720,elevation:p.elevation,facing:x<960?'left':'right',sourceNodeId:p.nodeId,destinationNodeId:destination,destinationConnectorId:`entry-${destination}`,interactionId:`interact-${id}`,transitionLabel:kind,requiresObjectiveCompletion:true,canonicalTransitionReason:`Continuidad canónica desde ${p.nodeId}`});
const anchor=(id:string,x:number,y:number,elevation:number):Anchor=>({id,x,y,elevation});
export const campaignWorldDefinitions:readonly LevelWorldDefinition[]=Object.freeze(profiles.map((p,index)=>{
 const width=p.vertical?1920:2240,height=p.vertical?1440:900;
 const sectors:EnvironmentSector[]=[0,1,2].map(i=>({sectorId:`${p.profile}-sector-${i+1}`,label:`${p.locationLabel} ${i+1}`,x:i*width/3,y:p.vertical?i*260:0,width:width/3,height:p.vertical?900:height,elevation:p.elevation+(p.vertical?-i*2:0)}));
 const environmentInstances=makeInstances(p,sectors), foregroundInstances=[{...environmentInstances[20],assetKey:worldAssetCatalog[(p.assetOffset+58)%70].key,role:'foreground' as const,depth:820,scrollFactorX:1.03,optionalVariant:`${p.profile}-foreground`}];
 const stair=p.vertical?[{stairId:'timed-descent-flight',x:300,y:300,width:1320,height:900,lowerX:1540,lowerY:1150,upperX:380,upperY:430,direction:'descending' as const,allowsAllies:true,allowsEnemies:true,landingIds:['landing-upper','landing-middle','landing-lower']}]:[];
 return {nodeId:p.nodeId,runtimeLevelId:p.runtimeLevelId,worldProfileId:p.profile,locationId:p.location,locationLabel:p.locationLabel,floorId:p.floor,floorLabel:p.floorLabel,elevationBase:p.elevation,worldWidth:width,worldHeight:height,cameraBounds:{x:0,y:0,width,height},entryConnectors:[connector(p,`entry-${p.nodeId}`,'door',96,index?profiles[index-1].nodeId:p.nodeId)],exitConnectors:[connector(p,`exit-${p.nodeId}`,p.connector,width-120,p.next)],walkableSurfaces:[{surfaceId:'primary-floor',x:0,y:720,width,height:64,elevation:p.elevation},...(p.vertical?[{surfaceId:'middle-landing',x:720,y:760,width:480,height:48,elevation:1},{surfaceId:'lower-floor',x:0,y:1150,width,height:64,elevation:-2}]:[])],stairZones:stair,platforms:[],environmentalSectors:sectors,environmentInstances,foregroundInstances,lightAnchors:[anchor('light-primary',width/2,220,p.elevation)],objectiveAnchors:[anchor(`objective-${p.profile}`,width*.62,p.vertical?900:690,p.elevation)],enemySpawnZones:[{id:`enemies-${p.profile}`,x:width*.3,y:p.vertical?400:580,width:width*.45,height:160,elevation:p.elevation}],allySpawnAnchors:[anchor('ally-primary',150,690,p.elevation)],pickupAnchors:[anchor('pickup-primary',width*.45,690,p.elevation)],landmarkIds:[p.landmark],minimapGeometry:{kind:p.minimap,sectors:sectors.map(({x,y,width,height})=>({x,y,width,height})),stairs:stair.map(s=>({fromX:s.upperX,fromY:s.upperY,toX:s.lowerX,toY:s.lowerY}))},rendererKind:'authored-level',legacyBackground:false} satisfies LevelWorldDefinition;
}));
