export type CorridorSector = 'service-entry' | 'teller-security' | 'dark-offices' | 'blocked-corridor' | 'exit-stairs';
export type CorridorEnvironmentRole = 'distant' | 'rearArchitecture' | 'wall' | 'rearDecor' | 'playfieldDecor' | 'prop' | 'foreground' | 'lightAnchor' | 'exitLandmark';
export interface CorridorEnvironmentInstance { assetKey:string; x:number; y:number; originX:number; originY:number; scaleX:number; scaleY:number; depth:number; scrollFactorX:number; scrollFactorY:number; flipX:boolean; alpha:number; sector:CorridorSector; role:CorridorEnvironmentRole; }
const i=(assetKey:string,x:number,y:number,sector:CorridorSector,role:CorridorEnvironmentRole,depth:number, extras:Partial<Omit<CorridorEnvironmentInstance,'assetKey'|'x'|'y'|'sector'|'role'|'depth'>>={}):CorridorEnvironmentInstance=>({assetKey,x,y,sector,role,depth,originX:0,originY:1,scaleX:1,scaleY:1,scrollFactorX:1,scrollFactorY:1,flipX:false,alpha:1,...extras});
export const corridorSectors: readonly CorridorSector[]=['service-entry','teller-security','dark-offices','blocked-corridor','exit-stairs'];
export const corridorEnvironmentComposition: readonly CorridorEnvironmentInstance[] = Object.freeze([
  i('corridor-corridor-wall-clean',0,800,'service-entry','wall',1),i('corridor-service-door',90,800,'service-entry','rearArchitecture',3),i('corridor-bank-signage',350,420,'service-entry','rearDecor',4),i('corridor-pipe-bundle',30,250,'service-entry','rearDecor',3),i('corridor-bank-bench',620,800,'service-entry','prop',7),i('corridor-trash-bin',920,800,'service-entry','prop',7),i('corridor-ceiling-light-cold',420,180,'service-entry','lightAnchor',5),i('corridor-floor-wet-strip',430,818,'service-entry','playfieldDecor',6),i('corridor-foreground-column',1060,864,'service-entry','foreground',820,{scrollFactorX:1.03,alpha:.86}),
  i('corridor-corridor-wall-clean',1120,800,'teller-security','wall',1,{flipX:true}),i('corridor-teller-window',1180,690,'teller-security','rearArchitecture',4),i('corridor-teller-window-broken',1600,690,'teller-security','rearArchitecture',4),i('corridor-security-bars',2020,800,'teller-security','rearArchitecture',5),i('corridor-paper-cluster',1450,810,'teller-security','prop',7),i('corridor-wall-cracks-a',1840,570,'teller-security','rearDecor',5),i('corridor-ceiling-light-cold',1370,170,'teller-security','lightAnchor',5),i('corridor-foreground-bars',2160,864,'teller-security','foreground',821,{scrollFactorX:1.02,alpha:.78}),
  i('corridor-corridor-wall-damaged',2240,800,'dark-offices','wall',1),i('corridor-office-window-dark',2300,650,'dark-offices','rearArchitecture',4),i('corridor-office-window-lit',2670,650,'dark-offices','rearArchitecture',4),i('corridor-security-door',3050,800,'dark-offices','rearArchitecture',4),i('corridor-humidity-stain',2520,770,'dark-offices','rearDecor',3),i('corridor-blood-smear',3020,770,'dark-offices','rearDecor',5),i('corridor-broken-furniture',2720,805,'dark-offices','prop',8),i('corridor-ceiling-light-emergency',2910,180,'dark-offices','lightAnchor',5),i('corridor-floor-damage',2380,818,'dark-offices','playfieldDecor',6),
  i('corridor-corridor-wall-damaged',3360,800,'blocked-corridor','wall',1,{flipX:true}),i('corridor-service-door',3440,800,'blocked-corridor','rearArchitecture',4,{flipX:true}),i('corridor-security-bars',3830,800,'blocked-corridor','rearArchitecture',5),i('corridor-debris-cluster',3590,812,'blocked-corridor','prop',8),i('corridor-broken-furniture',4030,810,'blocked-corridor','prop',8,{flipX:true}),i('corridor-wall-cracks-b',4170,570,'blocked-corridor','rearDecor',4),i('corridor-cable-tray',3480,250,'blocked-corridor','rearDecor',4),i('corridor-floor-damage',3950,818,'blocked-corridor','playfieldDecor',6),i('corridor-foreground-column',4410,864,'blocked-corridor','foreground',820,{scrollFactorX:1.03,flipX:true,alpha:.84}),
  i('corridor-corridor-wall-clean',4480,800,'exit-stairs','wall',1),i('corridor-exit-door',4630,800,'exit-stairs','exitLandmark',5),i('corridor-exit-sign',4660,390,'exit-stairs','exitLandmark',6),i('corridor-stairs-end',5050,810,'exit-stairs','exitLandmark',5),i('corridor-pipe-bundle',4720,250,'exit-stairs','rearDecor',3,{flipX:true}),i('corridor-ceiling-light-cold',4810,180,'exit-stairs','lightAnchor',5),i('corridor-floor-wet-strip',4810,818,'exit-stairs','playfieldDecor',6),i('corridor-trash-bin',4940,805,'exit-stairs','prop',7),i('corridor-foreground-bars',5480,864,'exit-stairs','foreground',821,{scrollFactorX:1.02,alpha:.72})
]);
