export interface BackdropCrop { x: number; y: number; width: number; height: number }
export interface LevelBackdropProfile { id:string; runtimeLevelId:string; backgroundAssetPath:string; optionalMidgroundAssetPath?:string; optionalForegroundAssetPath?:string; fitMode:'cover'|'contain'; crop:BackdropCrop; scale:number; origin:{x:number;y:number}; scrollFactor:{x:number;y:number}; tint:number; alpha:number; darkness:number; blur:false; locationLabel:string; floorLabel:string }
const profile=(value:LevelBackdropProfile)=>Object.freeze(value);
export const levelBackdropProfiles:Readonly<Record<string,LevelBackdropProfile>>=Object.freeze({
 level_1_comedor_resistencia:profile({id:'subsoil-dining-photo',runtimeLevelId:'level_1_comedor_resistencia',backgroundAssetPath:'/subsoil.jpg',fitMode:'cover',crop:{x:.02,y:.12,width:.9,height:.78},scale:1,origin:{x:.5,y:.5},scrollFactor:{x:.04,y:.02},tint:0xfff1d6,alpha:.96,darkness:.16,blur:false,locationLabel:'Comedor institucional',floorLabel:'Subsuelo 1'}),
 level_1_pasillos_escaleras_pb:profile({id:'stair-access-photo',runtimeLevelId:'level_1_pasillos_escaleras_pb',backgroundAssetPath:'/stairs.jpg',fitMode:'cover',crop:{x:.08,y:.04,width:.84,height:.92},scale:1,origin:{x:.5,y:.5},scrollFactor:{x:.08,y:.03},tint:0xffe8c2,alpha:.96,darkness:.2,blur:false,locationLabel:'Pasillos de servicio',floorLabel:'Acceso a Planta Baja'}),
 level_2_hall_planta_baja:profile({id:'ground-floor-hall-photo',runtimeLevelId:'level_2_hall_planta_baja',backgroundAssetPath:'/ground-floor.jpg',fitMode:'cover',crop:{x:.05,y:.08,width:.9,height:.82},scale:1,origin:{x:.5,y:.5},scrollFactor:{x:.05,y:.02},tint:0xffffff,alpha:.98,darkness:.13,blur:false,locationLabel:'Hall principal',floorLabel:'Planta Baja'}),
 level_3_segundo_piso:profile({id:'reconquista-sector-photo',runtimeLevelId:'level_3_segundo_piso',backgroundAssetPath:'/ground-floor-reconquista-sector.jpg',fitMode:'cover',crop:{x:.12,y:.04,width:.8,height:.88},scale:1,origin:{x:.5,y:.5},scrollFactor:{x:.07,y:.02},tint:0xfff2dc,alpha:.96,darkness:.18,blur:false,locationLabel:'Administración',floorLabel:'Segundo piso'}),
 level_4_tercer_piso:profile({id:'25may-sector-photo',runtimeLevelId:'level_4_tercer_piso',backgroundAssetPath:'/ground-floor-25may-sector.jpg',fitMode:'cover',crop:{x:.03,y:.1,width:.86,height:.8},scale:1,origin:{x:.5,y:.5},scrollFactor:{x:.06,y:.02},tint:0xffe5cf,alpha:.95,darkness:.22,blur:false,locationLabel:'Oficinas comprometidas',floorLabel:'Tercer piso'}),
 level_4_oficina_422_comedor_escaleras:profile({id:'rivadavia-dining-photo',runtimeLevelId:'level_4_oficina_422_comedor_escaleras',backgroundAssetPath:'/ground-floor-rivadavia-sector.jpg',fitMode:'cover',crop:{x:.1,y:.14,width:.82,height:.76},scale:1,origin:{x:.5,y:.5},scrollFactor:{x:.05,y:.02},tint:0xffedcf,alpha:.97,darkness:.15,blur:false,locationLabel:'Comedor superior',floorLabel:'Cuarto piso'}),
 level_5_oficinas_selene_descenso:profile({id:'entrance-belongings-photo',runtimeLevelId:'level_5_oficinas_selene_descenso',backgroundAssetPath:'/entrance.jpg',fitMode:'cover',crop:{x:.16,y:.05,width:.76,height:.9},scale:1,origin:{x:.5,y:.5},scrollFactor:{x:.08,y:.02},tint:0xffdfc4,alpha:.94,darkness:.24,blur:false,locationLabel:'Sector de pertenencias',floorLabel:'Quinto piso'}),
 level_6_pasillos_planta_baja_salidas:profile({id:'office-422-photo',runtimeLevelId:'level_6_pasillos_planta_baja_salidas',backgroundAssetPath:'/ground-floor-reconquista-sector.jpg',optionalMidgroundAssetPath:'/entrance.jpg',fitMode:'cover',crop:{x:.34,y:.12,width:.58,height:.76},scale:1,origin:{x:.5,y:.5},scrollFactor:{x:.09,y:.02},tint:0xffd9bd,alpha:.94,darkness:.25,blur:false,locationLabel:'Oficina 422',floorLabel:'Cuarto piso'}),
 level_8_pasillo_subsuelo2_escaleras_subsuelo3:profile({id:'timed-stairs-photo',runtimeLevelId:'level_8_pasillo_subsuelo2_escaleras_subsuelo3',backgroundAssetPath:'/stairs.jpg',optionalMidgroundAssetPath:'/subsoil.jpg',fitMode:'cover',crop:{x:.42,y:.02,width:.54,height:.96},scale:1,origin:{x:.5,y:.5},scrollFactor:{x:.1,y:.04},tint:0xffd2aa,alpha:.95,darkness:.28,blur:false,locationLabel:'Núcleo de escaleras',floorLabel:'Descenso a Subsuelo 3'}),
 level_9_verificacion_salidas:profile({id:'exit-verification-photo',runtimeLevelId:'level_9_verificacion_salidas',backgroundAssetPath:'/ground-floor-25may-sector.jpg',optionalForegroundAssetPath:'/ground-floor-rivadavia-sector.jpg',fitMode:'cover',crop:{x:.2,y:.2,width:.72,height:.7},scale:1,origin:{x:.5,y:.5},scrollFactor:{x:.06,y:.02},tint:0xffead5,alpha:.93,darkness:.25,blur:false,locationLabel:'Sector de salidas',floorLabel:'Subsuelo 2'})
});
export function getLevelBackdropProfile(runtimeLevelId:string){return levelBackdropProfiles[runtimeLevelId]}
