/** Spatial validation only. Campaign order remains owned by the canonical manifest. */
export type StairDirection='up'|'down';
export interface VerticalConnection {stairId:string;sourceNodeId:string;sourceRuntimeLevelId:string;sourceFloor:number;sourceDirection:StairDirection;sourceAnchor:{x:number;y:number};targetNodeId:string;targetRuntimeLevelId:string;targetFloor:number;targetDirection:StairDirection;targetSpawnId:string;transitionLabel:string}
export const VERTICAL_CONNECTION_CATALOG:readonly VerticalConnection[]=Object.freeze([
 {stairId:'hall-to-second',sourceNodeId:'lvl02-esc01-hall-planta-baja',sourceRuntimeLevelId:'level_2_hall_planta_baja',sourceFloor:0,sourceDirection:'up',sourceAnchor:{x:5900,y:724},targetNodeId:'lvl03-esc01-segundo-piso',targetRuntimeLevelId:'level_3_segundo_piso',targetFloor:2,targetDirection:'up',targetSpawnId:'level_3_segundo_piso-player-spawn',transitionLabel:'Ascenso al segundo piso'},
 {stairId:'second-to-third',sourceNodeId:'lvl03-esc01-segundo-piso',sourceRuntimeLevelId:'level_3_segundo_piso',sourceFloor:2,sourceDirection:'up',sourceAnchor:{x:6200,y:820},targetNodeId:'lvl04-esc01-tercer-piso',targetRuntimeLevelId:'level_4_tercer_piso',targetFloor:3,targetDirection:'up',targetSpawnId:'level_4_tercer_piso-player-spawn',transitionLabel:'Ascenso al tercer piso'},
 {stairId:'third-to-fourth',sourceNodeId:'lvl04-esc01-tercer-piso',sourceRuntimeLevelId:'level_4_tercer_piso',sourceFloor:3,sourceDirection:'up',sourceAnchor:{x:6500,y:860},targetNodeId:'lvl05-esc01-cuarto-piso-comedor',targetRuntimeLevelId:'level_4_oficina_422_comedor_escaleras',targetFloor:4,targetDirection:'up',targetSpawnId:'lvl05-esc01-cuarto-piso-comedor-player-spawn',transitionLabel:'Ascenso al cuarto piso'},
 {stairId:'fourth-to-fifth',sourceNodeId:'lvl05-esc01-cuarto-piso-comedor',sourceRuntimeLevelId:'level_4_oficina_422_comedor_escaleras',sourceFloor:4,sourceDirection:'up',sourceAnchor:{x:6100,y:1060},targetNodeId:'lvl06-esc01-quinto-piso-pertenencias',targetRuntimeLevelId:'level_5_oficinas_selene_descenso',targetFloor:5,targetDirection:'up',targetSpawnId:'lvl06-esc01-quinto-piso-pertenencias-player-spawn',transitionLabel:'Ascenso al quinto piso'},
 {stairId:'fifth-to-office-422',sourceNodeId:'lvl06-esc01-quinto-piso-pertenencias',sourceRuntimeLevelId:'level_5_oficinas_selene_descenso',sourceFloor:5,sourceDirection:'down',sourceAnchor:{x:6700,y:980},targetNodeId:'lvl07-esc01-oficina-422-rescate',targetRuntimeLevelId:'level_6_pasillos_planta_baja_salidas',targetFloor:4,targetDirection:'down',targetSpawnId:'lvl07-esc01-oficina-422-rescate-player-spawn',transitionLabel:'Descenso a oficina 422'},
 {stairId:'office-422-to-sublevels',sourceNodeId:'lvl07-esc01-oficina-422-rescate',sourceRuntimeLevelId:'level_6_pasillos_planta_baja_salidas',sourceFloor:4,sourceDirection:'down',sourceAnchor:{x:7300,y:1060},targetNodeId:'lvl08-esc01-descenso-con-temporizador',targetRuntimeLevelId:'level_8_pasillo_subsuelo2_escaleras_subsuelo3',targetFloor:-2,targetDirection:'down',targetSpawnId:'lvl08-esc01-descenso-con-temporizador-player-spawn',transitionLabel:'Descenso al núcleo de subsuelos'}
]);
export function validateVerticalConnection(connection:VerticalConnection):boolean{return connection.sourceDirection==='up'?connection.targetFloor>connection.sourceFloor:connection.targetFloor<connection.sourceFloor}
