using System; using UnityEngine; using NWD.Core;
namespace NWD.Combat {
 [CreateAssetMenu(menuName="NWD/Weapon")] public sealed class WeaponDefinition:ScriptableObject { public string weaponId; public bool melee; public float damage=20, headshotMultiplier=2, range=80, spread=.01f, recoil=1, noiseRadius=25; public int magazineSize=12; }
 public sealed class HealthComponent:MonoBehaviour,IDamageable { [SerializeField]float maximum=100; public float Current{get;private set;} public bool Dead=>Current<=0; public event Action Died; void Awake()=>Current=maximum; public void ApplyDamage(DamageInfo d){if(Dead)return;Current=Mathf.Max(0,Current-d.Amount*(d.Headshot?2:1));if(Dead)Died?.Invoke();} }
 public readonly struct NoiseEvent { public readonly Vector3 Position; public readonly float Intensity,Radius,Duration; public readonly NoiseCategory Category; public readonly GameObject Owner; public NoiseEvent(Vector3 p,float i,float r,float d,NoiseCategory c,GameObject o){Position=p;Intensity=i;Radius=r;Duration=d;Category=c;Owner=o;} }
 public enum NoiseCategory { Gunshot,Melee,Sprint,BrokenObject,Alarm,Narrative }
 public static class NoiseSystem { public static event Action<NoiseEvent> Emitted; public static void Emit(NoiseEvent e)=>Emitted?.Invoke(e); }
 public sealed class NoiseEmitter:MonoBehaviour { public void Emit(NoiseCategory c,float intensity,float radius,float duration)=>NoiseSystem.Emit(new NoiseEvent(transform.position,intensity,radius,duration,c,gameObject)); }
 public sealed class HitscanResolver { public bool Resolve(Ray ray,float range,float damage,GameObject source){if(!Physics.Raycast(ray,out var hit,range))return false;var target=hit.collider.GetComponentInParent<IDamageable>();target?.ApplyDamage(new DamageInfo(damage,hit.point,source,hit.collider.CompareTag("Head")));return target!=null;} }
 public sealed class FirearmController:MonoBehaviour { [SerializeField]WeaponDefinition definition; [SerializeField]Camera aimCamera; int magazine,reserve=60; readonly HitscanResolver hitscan=new(); public int Magazine=>magazine; public int Reserve=>reserve; void Awake()=>magazine=definition?definition.magazineSize:0; public bool Fire(){if(magazine<=0||!definition)return false;magazine--;var ray=aimCamera?new Ray(aimCamera.transform.position,aimCamera.transform.forward):new Ray(transform.position,transform.forward);hitscan.Resolve(ray,definition.range,definition.damage,gameObject);NoiseSystem.Emit(new NoiseEvent(transform.position,1,definition.noiseRadius,1,NoiseCategory.Gunshot,gameObject));return true;} public int Reload(){var n=Mathf.Min(definition.magazineSize-magazine,reserve);magazine+=n;reserve-=n;return n;} }
 public sealed class MeleeWeaponController:MonoBehaviour { public WeaponDefinition definition; public bool Strike(Ray ray)=>new HitscanResolver().Resolve(ray,definition.range,definition.damage,gameObject); }
 public sealed class SurfaceImpactResolver:MonoBehaviour { public void Resolve(RaycastHit hit){} }
}
