import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { corridorEnvironmentAssets } from '../src/config/corridorEnvironmentAssets.ts';
import { corridorEnvironmentComposition, corridorSectors } from '../src/config/corridorEnvironmentComposition.ts';

const read = (path:string) => fs.readFileSync(new URL(path, import.meta.url),'utf8');
test('catalog contains valid local text SVG assets with no external resources',()=>{assert.ok(corridorEnvironmentAssets.length>=20);for(const asset of corridorEnvironmentAssets){assert.match(asset.path,/\.svg$/);assert.ok(asset.intendedWidth>0&&asset.intendedHeight>0);const svg=read(`../public/${asset.path}`);assert.match(svg,/^<svg/);assert.match(svg,/shape-rendering="crispEdges"/);assert.doesNotMatch(svg,/<image|<script|<foreignObject|\bhref=/i);assert.doesNotMatch(svg,new RegExp('data'+':|base'+'64','i'));}});
test('composition is deterministic, uses every catalog key, and spans five distinct sectors',()=>{assert.equal(corridorSectors.length,5);assert.deepEqual(new Set(corridorEnvironmentComposition.map(i=>i.sector)),new Set(corridorSectors));const used=new Set(corridorEnvironmentComposition.map(i=>i.assetKey));assert.deepEqual(used,new Set(corridorEnvironmentAssets.map(a=>a.key)));assert.ok(corridorEnvironmentComposition.every(i=>Number.isInteger(i.x)&&Number.isInteger(i.y)));});
test('renderer uses images and never architecture primitives',()=>{const source=read('../src/systems/CorridorEnvironmentRenderer.ts');assert.match(source,/scene\.add\.image/);assert.doesNotMatch(source,/scene\.add\.(?:rectangle|ellipse|graphics|text)/);assert.match(source,/architecturePrimitiveCount:0/);});
test('corridor bypasses legacy background while other levels retain it',()=>{const source=read('../src/scenes/GameScene.ts');assert.match(source,/selectedLevelId === AUTHORED_CORRIDOR_LEVEL_ID/);assert.match(source,/if \(usesAuthoredCorridor\)[\s\S]*?CorridorEnvironmentRenderer[\s\S]*?else \{\s*this\.drawSubsueloBackground/);assert.match(source,/environmentRenderer.*corridor-authored.*legacy/);assert.match(source,/legacyBackgroundActive.*!usesAuthoredCorridor/);});
test('canonical campaign remains at 35 nodes and corridor identity is unchanged',()=>{const campaign=JSON.parse(read('../public/assets/campaign/canonical_campaign_manifest.json'));assert.equal(campaign.nodes.length,35);const runtime=JSON.parse(read('../public/assets/levels/runtime/level_1_pasillos_escaleras_pb.runtime.json'));assert.equal(runtime.level_id,'level_1_pasillos_escaleras_pb');});
test('binary guard is installed in package scripts and normal workflow',()=>{const pkg=JSON.parse(read('../package.json'));assert.equal(pkg.scripts['audit:no-binary-diff'],'node scripts/auditNoBinaryDiff.mjs');assert.match(read('../../.github/workflows/production-gate.yml'),/audit:no-binary-diff/);});
