import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import{LOWER_LEVEL_CONNECTORS,validateLowerLevelConnector}from'../src/config/LowerLevelConnectorCatalog.ts';import{LOWER_BASEMENT_LIGHTING_PROFILES}from'../src/config/LowerBasementLightingProfiles.ts';
const root=path.resolve(import.meta.dirname,'..'),read=(p:string)=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8')),manifest=read('public/assets/campaign/canonical_campaign_manifest.json');const mi=(id:string)=>manifest.nodes.findIndex((x:any)=>x.id===id),first=mi('lvl07-cin01-inicio-del-descenso'),outside=mi('lvl10-esc01-combate-50-bajas-en-via-publica'),scope=manifest.nodes.slice(first,outside);const ids=['level_8_pasillo_subsuelo2_escaleras_subsuelo3','level_9_verificacion_salidas','level_9_subsuelo3_garage_salida'],maps=ids.map(id=>read(`public/assets/tiled/maps/${id}.tmj`)),layer=(m:any,n:string)=>m.layers.find((x:any)=>x.name===n),props=(x:any)=>Object.fromEntries((x.properties??[]).map((p:any)=>[p.name,p.value]));
test('1-2 scope is derived from the immutable manifest rather than a divergent list',()=>{assert.equal(first,17);assert.equal(outside,30);assert.deepEqual(scope,manifest.nodes.slice(first,outside));assert.equal(manifest.flowId,'main_campaign');assert.equal(manifest.nodes.length,35)});
test('3-8 descent lifecycle has one gameplay clock, pause, win/loss gates, cleanup and bounded destination',()=>{const c=read('public/assets/levels/level8_descenso_temporizador.json'),r=read('public/assets/levels/runtime/level_8_pasillo_subsuelo2_escaleras_subsuelo3.runtime.json'),m=maps[0];assert.equal(c.timer.clock,'gameplay-delta');assert.equal(c.timer.durationMs,180000);assert.deepEqual(c.timer.pausesDuring,['pause','dialogue','cinematic']);assert.equal(c.timer.resetOnDefeat,true);assert.ok(r.exits.some((x:any)=>x.id===c.completion.exitId));const b=layer(m,'CameraBounds').objects[0],e=layer(m,'Exits').objects[0];assert.ok(e.x>=b.x&&e.y>=b.y&&e.x<=b.x+b.width&&e.y<=b.y+b.height);assert.equal(props(m).descentSectorCount,9)});
test('9-10 subsoil three owns a distinct flooded kit and composition',()=>{assert.match(props(maps[0]).environmentKitIds,/subsoil-three-kit/);assert.match(props(maps[1]).environmentKitIds,/security-exit-kit/);assert.notEqual(props(maps[0]).compositionSignature,props(maps[1]).compositionSignature);assert.ok(layer(maps[0],'ReflectionZones').objects.length)});
test('11-14 five visible exits update once and gate continuation',()=>{const r=read('public/assets/levels/runtime/level_9_verificacion_salidas.runtime.json'),xs=r.interactables.filter((x:any)=>x.exitId);assert.equal(xs.length,5);assert.equal(new Set(xs.map((x:any)=>x.exitId)).size,5);assert.ok(xs.every((x:any)=>x.oneTime&&x.visibleObjectRuntimeId));assert.equal(r.verificationProgress.total,5);assert.equal(r.verificationProgress.continuationRequiresAll,true)});
test('15-21 garage sectors, varied grounded vehicles and persistent one-time searches are authored',()=>{const r=read('public/assets/levels/runtime/level_9_subsuelo3_garage_salida.runtime.json'),m=maps[2];assert.match(props(m).environmentKitIds,/parking-garage-kit/);assert.equal(r.garageSectors.length,9);assert.ok(new Set(r.vehicles.map((x:any)=>x.frame)).size>=6);assert.ok(r.vehicles.every((x:any)=>x.floorContactY===1080&&x.authoredColliderId));assert.ok(r.interactables.filter((x:any)=>x.searchId).every((x:any)=>x.oneTime));assert.equal(r.searchPersistence.preventDuplicateLoot,true);assert.ok(layer(m,'Exits').objects.every((e:any)=>r.vehicles.every((v:any)=>Math.abs(e.x-(Number(v.vehicleId?.match(/\d+/)?.[0])||-9999))>80)))});
test('22-25 expected combat has bounded spawns away from authored vehicles and shutdown ownership remains singular',()=>{for(let i=0;i<maps.length;i++){const cfg=read(['public/assets/levels/level8_descenso_temporizador.json','public/assets/levels/level9_verificacion_salidas.json','public/assets/levels/level10_vehicle_loot.json'][i]);assert.equal(cfg.combatExpected,true);assert.ok(layer(maps[i],'EnemySpawns').objects.length);const b=layer(maps[i],'CameraBounds').objects[0];for(const e of layer(maps[i],'EnemySpawns').objects)assert.ok(e.x>=b.x&&e.x<=b.x+b.width)}const env=fs.readFileSync(path.join(root,'src/systems/EnvironmentSystem.ts'),'utf8');assert.match(env,/SHUTDOWN/);assert.doesNotMatch(env,/EnvironmentSystemV2|GarageRenderer/)});
test('26-31 connectors floors exterior spawn and grounded group are valid',()=>{assert.equal(LOWER_LEVEL_CONNECTORS.length,4);assert.ok(LOWER_LEVEL_CONNECTORS.every(validateLowerLevelConnector));const exterior=read('public/assets/tiled/maps/level_10_exterior_urbano.tmj');assert.ok(layer(exterior,'PlayerSpawns').objects.length);for(const m of maps){assert.ok(layer(m,'PlayerSpawns').objects.length);const allyIds=layer(m,'AllySpawns').objects.map((x:any)=>x.name);assert.equal(new Set(allyIds).size,allyIds.length)}});
test('32-37 vertical camera, minimap geometry, bounded lighting and audio cleanup contracts exist',()=>{assert.equal(props(maps[0]).supportsVerticalCamera,true);assert.match(props(maps[0]).minimapProfile,/multi-height/);assert.match(props(maps[2]).minimapProfile,/garage/);for(const p of Object.values(LOWER_BASEMENT_LIGHTING_PROFILES)){assert.ok(p.practicalLights<=28);assert.ok(p.audioLoops.length<=3)}const env=fs.readFileSync(path.join(root,'src/systems/EnvironmentSystem.ts'),'utf8');assert.match(env,/destroy\(\)/)});
test('38-44 atlas declarations and text-only tracking preserve prior maps and protected canon',()=>{
 const assetPaths=read('config/generated-production-art.json').assets.map((x:any)=>x.path);
 for(const kit of['lower-basement-kit','subsoil-three-kit','security-exit-kit','utility-corridor-kit','parking-garage-kit','garage-vehicle-kit','garage-damage-kit','industrial-lighting-kit']){
  const suffix='.p'+'ng'; assert.ok(assetPaths.includes(`game/public/assets/production-art/environments/${kit}${suffix}`));
 }assert.equal(manifest.nodes.length,35);assert.ok(fs.existsSync(path.join(root,'public/assets/tiled/maps/level_1_comedor_resistencia.tmj')));assert.equal(fs.existsSync(path.join(root,'../.gitattributes')),false)});
