import test from 'node:test';import assert from 'node:assert/strict';import fs from'node:fs';import path from'node:path';
import { isCampaignQaRequested, QA_CAMPAIGN_STORAGE_NAMESPACE } from '../src/qa/CampaignQaMode.ts';import { CanonicalNodes19To27Runtime } from '../src/campaign/canonicalNodes19To27.ts';import { combatProfiles } from '../src/config/CombatProfiles.ts';import { levelBackdropProfiles } from '../src/config/LevelBackdropProfiles.ts';import { UI_LAYOUT } from '../src/scenes/uiLayout.ts';
const root=path.resolve(import.meta.dirname,'..');const manifest=JSON.parse(fs.readFileSync(path.join(root,'public/assets/campaign/canonical_campaign_manifest.json'),'utf8'));
test('QA navigator is query gated and isolated',()=>{assert.equal(isCampaignQaRequested(''),false);assert.equal(isCampaignQaRequested('?qaCampaign=1'),true);assert.notEqual(QA_CAMPAIGN_STORAGE_NAMESPACE,'nwd:campaign')});
test('timed descent success, pause, loss and restart are distinct',()=>{const r=new CanonicalNodes19To27Runtime();assert.equal(r.formatTimer(),'3:00');r.tick(1000,true);assert.equal(r.formatTimer(),'3:00');r.tick(1000);assert.equal(r.formatTimer(),'2:59');assert.equal(r.completeDescent(),true);assert.equal(r.getSnapshot().descent.state,'won');assert.equal(r.completeDescent(),false);const lost=new CanonicalNodes19To27Runtime();lost.tick(180000);assert.equal(lost.getSnapshot().descent.state,'lost');assert.equal(lost.completeDescent(),false);lost.restartDescent();assert.equal(lost.formatTimer(),'3:00')});
test('every canonical level has configured combat and bounded spawns',()=>{for(const node of manifest.nodes.filter((n:any)=>n.type==='level')){assert.ok(combatProfiles[node.id]);const wrapper=JSON.parse(fs.readFileSync(path.join(root,'public',node.levelConfigPath),'utf8'));assert.equal(wrapper.combatProfileId,combatProfiles[node.id].id);const runtime=JSON.parse(fs.readFileSync(path.join(root,'public',wrapper.runtimePath),'utf8'));assert.ok(runtime.spawn_zones.points.length>0);for(const p of runtime.spawn_zones.points){assert.ok(p.x>=0&&p.x<=runtime.layout.width);assert.ok(p.y>=0&&p.y<=runtime.layout.height)}}});
test('descent target is derived from canonical next node',()=>{const i=manifest.nodes.findIndex((n:any)=>n.id==='lvl08-esc01-descenso-con-temporizador');const wrapper=JSON.parse(fs.readFileSync(path.join(root,'public',manifest.nodes[i].levelConfigPath),'utf8'));assert.equal(wrapper.nextNodeId,manifest.nodes[i+1].id);assert.equal(manifest.nodes[i+1].id,'lvl08-cin01-damian-infectado-y-suicidio')});
test('backdrops are concrete, proportional and HUD meets budgets',()=>{assert.equal(Object.keys(levelBackdropProfiles).length,10);for(const p of Object.values(levelBackdropProfiles)){assert.equal(p.blur,false);assert.ok(p.crop.width>0&&p.crop.width<=1);assert.ok(p.crop.height>0&&p.crop.height<=1);assert.ok(p.fitMode==='cover'||p.fitMode==='contain')}assert.ok(UI_LAYOUT.protagonistWidth<=255&&UI_LAYOUT.protagonistHeight<=92);assert.ok(UI_LAYOUT.partyWidth<=255&&UI_LAYOUT.partyHeight<=92);assert.ok(UI_LAYOUT.minimapWidth<=176&&UI_LAYOUT.minimapHeight<=96);assert.ok(UI_LAYOUT.objectiveWidth<=520&&UI_LAYOUT.objectiveHeight<=62)});
test('canonical story manifest remains 35 nodes',()=>{assert.equal(manifest.flowId,'main_campaign');assert.equal(manifest.nodes.length,35)});
