import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs';
import { resolveVisualGeneration, visualV2Style } from '../src/config/visualStyle.ts';
import { characterVisualsV2 } from '../src/config/characterVisualsV2.ts';
import { corridorVisualV2 } from '../src/config/environmentVisualsV2.ts';
test('visual manifest paths, dimensions and animations are valid',()=>{const m=JSON.parse(fs.readFileSync(new URL('../public/assets/visual-v2/visual_manifest.json',import.meta.url),'utf8'));assert.ok(m.assets.length>=10);for(const a of m.assets){assert.ok(fs.existsSync(new URL(`../public/${a.path}`,import.meta.url)));assert.equal(a.dimensions.width,a.frameWidth*a.frames);for(const anim of Object.values(a.animations) as any[])assert.ok(anim.end<a.frames);}});
test('v2 is isolated to the canonical corridor',()=>{assert.equal(resolveVisualGeneration('level_1_pasillos_escaleras_pb','v2'),'v2');assert.equal(resolveVisualGeneration('anything-else','v2'),'legacy');});
test('characters expose the centralized attachment contract',()=>{for(const visual of Object.values(characterVisualsV2))for(const key of ['handOffset','secondaryHandOffset','muzzleOffset','shellEjectionOffset','nameplateOffset','healthBarOffset','shadowOffset'])assert.ok(key in visual.attachments);});
test('minimap and bounded effects have production configuration',()=>{assert.equal(corridorVisualV2.bounds.width,5600);assert.equal(corridorVisualV2.rooms.length,3);assert.ok(Object.values(visualV2Style.budgets).every(v=>v>0&&v<=48));});
test('visual-v2 ships only reviewable text assets',()=>{const root=new URL('../public/assets/visual-v2/',import.meta.url);const manifest=JSON.parse(fs.readFileSync(new URL('visual_manifest.json',root),'utf8'));for(const asset of manifest.assets){assert.match(asset.path,/\.svg$/);const bytes=fs.readFileSync(new URL(`../public/${asset.path}`,import.meta.url));assert.equal(bytes.includes(0),false);assert.match(bytes.toString('utf8'),/^<svg/);}});
